### PR TITLE
Added Python3 support

### PR DESCRIPTION
**Pull request by Skylion007**
I added Python3 support while trying to maintain Python2 support as well. The only major changes to the code base consist of adding "." to relative imports as Python3 required, modifying the decode since Python3 no longer has that feature (since everything switched to Python3) and changing a single exception's syntax. If there is anything else I need to do to add Python 3 support let me know.

### CODE REVIEW

**Comment by tokland** [comment]
I thought the API was only python2 (https://github.com/google/google-api-python-client/issues/3). Do you know the current status?

**Comment by tokland** [comment]
I couldn't make it work for Python 2.7, can you check it?

`
$ PYTHONPATH=. python2 bin/youtube-upload --title "Title" --playlist "Test playlist" test.mp4  
Traceback (most recent call last):
  File "bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
  File "/home/arnau/src/youtube-upload/youtube_upload/main.py", line 26, in <module>
    from . import auth
  File "/home/arnau/src/youtube-upload/youtube_upload/auth/__init__.py", line 10, in <module>
    from youtube_upload.auth import console
  File "/home/arnau/src/youtube-upload/youtube_upload/auth/console.py", line 2, in <module>
    from builtins import input
ImportError: No module named builtins
`

**Comment by Skylion007** [comment]
Interesting, it should work for Python2. I will commit a much simpler workaround. As for Python 3.4.3, I suppose that is a Unix error (with the whole Unicode vs bytes distinction in Python3). I have been testing it on Windows, so that was why Python3 failed on Linux. This should work though. If not, let me know and I'll try to fix it.

**Comment by tokland** [comment]
It works, thx! I would have written some auxiliar funcions instead of inline coding, but ok, there is always time to do that :)

**Comment by Skylion007** [comment]
Might want to update the readme now that Python 3 is supported.

**Comment by tokland** [comment]
indeed: 68d643c

**Pull request merged**
