### PR TITLE
Scheduled publishing

### PR DESCRIPTION
**Pull request by Bene81**
- Added command line option for scheduled publishing. Allows you to upload a video now and let youtube publish it on a certain date/time. Requires privacy status to be set to 'private' or upload will fail.
- Set privacy status to 'private' per default. Skip this change if you don't like it.

Best regards

Bene81

### CODE REVIEW

**Comment by tokland** [comment]
Great, thx. I'd propose 2 changes:

- option name: publish-at
- privacy: 1) leave it "public" by default. 2) If publish-at present and no privacy given, use "private" (with a debug message). 3) If publish-at present and privacy given and this privacy is not "private", raise exception OptionsMissing (we can rename it to OptionsError).

**Comment by Bene81** [comment]
Okay, I'll see what I can do.
When I find some spare time that is ;-).
May take a few days.

**Comment by tokland** [comment]
You're right, it can be simplified. Check 3e9e4015. Thx!

**Comment by Bene81** [comment]
Well, thank you for taking the time and effort to modify and integrate my little contribution. Too bad I don't really know python. Thanks for the improvements.

**Pull request merged**
