### PR TITLE
Add option to automatically open webpage when video uploads

### PR DESCRIPTION
**Pull request by Skylion007**
Added a command line argument that opens the video's webpage when the video finishes uploading. Although not implemented, this could also be used for the verification link if qtwebkit is not installed. 

Also, fixes a small Python3 issue with some interpreters requiring explicit imports while others do not.

### CODE REVIEW

**Comment by tokland** [comment]
Sorry, I'd prefer not to add this browser option, the video ID is returned so the user can do whatever he wants with it.

**Comment by Skylion007** [comment]
It's an optional argument though. As in it won't happen unless the user uses the --open-link flag

**Comment by Skylion007** [comment]
Does this most recent clarification change your mind at all?

**Comment by tokland** [comment]
Yes, optional, of course. But... I don't know, the browser won't even have a session to edit the video. Is that difficult in Windows? In UNIX you'd simply write:

```
firefox "https://www.youtube.com/watch?v=$(youtube-upload ...)"
```

**Comment by Skylion007** [comment]
Tokland while you can implement something like that in Windows it is much more difficult. More importantly though is that it is extremely difficult to do error handling like this and rather unintuitive. 

Remember, Windows does not properly employ exit status code. Also, by default in Windows STDOUT and STDIN read in text only mode (a leftover standard from 1977 I think), and as such interoperability between application in this manner is much more difficult. 

For the record, the way you have done that by combining string arguments is not possible to my knowledge in command line or at the very least is an extremely high level feature.

So while this may be a viable solution for a UNIX user, it is not for a Windows. You MAY be able to do something similar with a bash script, but that would require a separate executable that would need to have it's own way to parse arguments.

For the sake of the user, I strongly recommend that you pull it. After all, what's the point of the --auth-browser option if you can do authorization from commandline? Because it is much easier for the end user.

Finally, even highlighting and copying text from the Windows commandline is difficult as it is not even that well supported by Microsoft.

For all these reasons listed above, I would strongly suggest you add in this option. At the worst it will add a redundant feature, at best it will make the application much easier to use, increase the user base and potentially lead to an increase in donations, contributions, and overall traffic.

**Comment by tokland** [comment]
Ok, merged.

**Pull request merged**
