### PR TITLE
importing file from oauth client

### LINKED ISSUE #262: AttributeError: module 'oauth2client' has no attribute 'file' - Main.py missing import?
Had the following issue on my computer in both Ubuntu and Windows using Python 3.7.0.

```
C:\youtube-upload-master>python C:\youtube-upload-master\youtube-upload --title="Test" D:\OUT.mp4
Using client secrets: C:\Users\Mark\.client_secrets.json
Using credentials file: C:\Users\Mark\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\youtube-upload-master\youtube-upload", line 10, in <module>
    main.run()
  File "C:\youtube-upload-master\youtube_upload\main.py", line 257, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\youtube-upload-master\youtube_upload\lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 251, in main
    run_main(parser, options, args)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 170, in run_main
    youtube = get_youtube_handler(options)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 156, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\youtube-upload-master\youtube_upload\auth\__init__.py", line 38, in get_resource
    storage = oauth2client.file.Storage(credentials_file)
AttributeError: module 'oauth2client' has no attribute 'file'
```

I have installed the script before on previous computers and never had any problem. To resolve this issue I put "from oauth2client import file" in main.py and I had no issue after that.

Not sure if this is related to the main setup with the client secrets and credential file. In the error I posted above it says it is using a credentials file but I know that file doesn't even exist yet because I didn't get the whole portion where the script asks you to follow the link and paste in the code. Once I added that import line in the main.py the script functioned like normal as shown below.

```
C:\youtube-upload-master>python C:\youtube-upload-master\youtube-upload --title="Test" D:\OUT.mp4
Using client secrets: C:\Users\Mark\.client_secrets.json
Using credentials file: C:\Users\Mark\.youtube-upload-credentials.json
C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\Mark\.youtube-upload-credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Check this link in your browser: https://accounts.google.com/o/oauth2/auth?client_id=529489928594-597ekj6pf1uni9n9lmjgft07ian76gvv.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&access_type=offline&response_type=code
Enter verification code: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Start upload: D:\OUT.mp4
```

The thing that I found strange is I never had this problem on two other computers I set this up on three months ago only till today when I installed python and attempted to set it up on this computer did I have this problem and couldn't figure out why.

### PR DESCRIPTION
**Pull request by yisraeldov**
fixes #262

### CODE REVIEW

**Comment by msegzda** [comment]
Please merge 👍

**Comment by yisraeldov** [comment]
@msegzda  I think that the owner of the project, @tokland  has vanished. Should get another maintainer.

**Comment by tokland** [comment]
I am not maintaining this package anymore. If anyone is willing to the job,
I'll add a link in the readme.

**Comment by tokland** [comment]
I am not maintaining this package anymore. If anyone is willing to the job,
I'll add a link to the fork in the readme.

**Comment by yisraeldov** [comment]
Can we maybe start a group fork and have a few maintainers so it doesn't turn into vapor ware. 

youtube-upload/youtube-upload 

I don't know how easy it is to do in git hub , but gitlab it is

**Comment by remorses** [comment]
If you search an alternative I made a similar lib that takes options from yaml file instead of command arguments, https://github.com/remorses/youtube-video-upload

**Comment by yisraeldov** [comment]
Can we maybe start a group fork and have a few maintainers so it doesn't
turn into vapor ware.

youtube-upload/youtube-upload

**Comment by kootsoop** [comment]
Sorry, I didn't see this pull request until just now.  I believe I've made the change you've done.

**Pull request closed without merging**
